import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import DashboardNavbar from "@/components/dashbord/user/DashboardNavbar";
// import { getServerSession } from "next-auth";
// import { redirect } from "next/navigation";
// import { authOptions } from "../api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Photo studio",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // ✅ get session securely on the server
  const session = await getServerSession(authOptions);

  // ✅ redirect unauthenticated users to login
  if (!session) {
    redirect("/auth"); // Or wherever your login page is
  }
  return (
    <section
      className={`font-montserrat flex min-h-screen w-full bg-black flex-col`}
    >
      <div className='w-full flex-col'>
        <div className='flex justify-center items-center bg-black w-full flex-col'>
          <DashboardNavbar />
        </div>
        <div className='max-h-screen sm:overflow-y-scroll bg-black'>
          {children}
        </div>

      </div>
    </section>
  );
}
