import type { Metadata } from "next";
import Navbar from "@/components/navbar/Navbar";
import DashboardSideBar from "@/components/dashbord/DashboardSideBar";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "../api/auth/[...nextauth]/route";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // ✅ get session securely on the server
  const session = await getServerSession(authOptions);

  // ✅ redirect unauthenticated users to login
  if (!session) {
    redirect("/auth"); // Or wherever your login page is
  }
  return (

    <section
      className={`font-montserrat bg-[#FAFAFA] w-full `}
    >

      <Navbar />
      <section className="flex gap-5 items-start p-20 py-32">
        <DashboardSideBar />
        <section className="w-full max-h-screen overflow-y-scroll">{children}</section>
      </section>
    </section>
  );
}
