
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Sign In | Sign Up",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="flex relative flex-col w-full min-h-screen bg-[url('/auth/auth-image.jpg')] bg-green-200 overflow-y-hidden justify-center bg-no-repeat px-5 w-full">
      {/* <ThemeToggle /> */}

      <div className="absolute w-full bg-black/30 z-10 top-0 bottom-0 h-full"></div>

      <div className="relative z-20">
        {children}
      </div>
      </section>

  );
}
